; FOR TEST RUNS ONLY -- DO NOT USE IN PRODUCTION
; Start with: OpenSim.exe -inifile OpenSim.Tests.ini

[Const]
    BaseHostname = "127.0.0.1"
    BaseURL = http://${Const|BaseHostname}
    PublicPort = "9000"
    PrivURL = ${Const|BaseURL}
    PrivatePort = "8003"

[Startup]
    ConsoleHistoryFileEnabled = false

[Architecture]
    Include-Architecture = "config-include/Standalone.Tests.ini"
